### ISSUE TITLE
Copy issue

### ISSUE THREAD

**Issue by mgenedy** [divad/bargate#98] opened 2017-12-20 16:01 UTC
Dears
I can't copy any file, kindly find below Debug

2017-12-20 18:01:46,342 INFO: User "mgenedy" connected to "smb://file-server.tanmeyah.lan/" using func name "TANMEYAH" and action "copy" using POST and path "IT/PolicyDefinitions.zip" from "172.27.0.108" using Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0
2017-12-20 18:01:47,516 ERROR: 
Title:                Internal Error
Message:              An internal error has occured and has been forwarded to our support team.
Exception Type:       <type 'exceptions.ValueError'>
Exception Message:    (22, 'Invalid argument')
HTTP Path:            /tanmeyah
HTTP Method:          POST
Client IP Address:    172.27.0.108
User Agent:           Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0
User Platform:        linux
User Browser:         firefox
User Browser Version: 52.0
Username:             mgenedy

Traceback:

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/bargate/lib/smb.py", line 948, in connection
    libsmbclient.stat(dest)
ValueError: (22, 'Invalid argument')

**Comment by divad** [comment] 2017-12-21 08:52
Sadly, this error often is often generated when the remote server has thrown an odd error. 

What is the remote server software?

**Comment by mgenedy** [comment] 2017-12-21 09:00
Dear Divad,
Thanks for quick reply, kindly find below needed info:
Remote Server software:  samba4 working as file server only and joind the domain which is samba4 too .
Remote Server software Version: samba-4.6.4

**Comment by divad** [comment] 2017-12-22 17:38
Duplicate of #97

**Closed by divad** 2017-12-22 17:38 UTC
